# fly.toml app configuration file generated for agenda-project-golden-canyon-2416 on 2026-05-11T13:41:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agenda-project-golden-canyon-2416'
primary_region = 'gru'
console_command = '/rails/bin/rails console'

[build]

[env]
  PORT = '8080'

[processes]
  app = './bin/rails server'
  solidq = 'bundle exec rake solid_queue:start'

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '60s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '2gb'
  cpus = 2
  memory_mb = 2048
